### ISSUE TITLE
404 Profile Photo

### ISSUE THREAD

**Issue by LaksCastro** [scarleatt/scarleatt.github.io#1]
your profile photo on menu is not working, be showing a crashed img :(

![Captura de Tela (5)](https://user-images.githubusercontent.com/51419598/76471264-9608f580-63c8-11ea-8ea8-59e4f1d568b1.png)

**Comment by scarleatt** [comment]
Access to github in China will slow down, you can refresh it a few more times, and the avatar will be displayed.
